name: color_pop
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.10.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Bộ icon theo phong cách iOS (Cupertino) được Flutter cung cấp
  # Dùng với CupertinoIcons.<icon_name>
  cupertino_icons: ^1.0.8

  # Thư viện quản lý trạng thái theo mô hình BLoC (Business Logic Component)
  # Giúp tách biệt UI và business logic, dễ bảo trì và kiểm thử
  flutter_bloc: ^9.1.1

  # Hỗ trợ so sánh giá trị giữa các object thay vì so sánh địa chỉ bộ nhớ
  # Thường dùng cho State, Event, Model trong BLoC để tối ưu rebuild
  equatable: ^2.0.7
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  sqflite: ^2.4.2+1
  path: ^1.9.1
  path_provider: ^2.1.6
  image_picker: ^1.2.3
  image: ^4.8.0
  gal: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/mock_data/
    - assets/images/avatars/
    - assets/images/categories/
    - assets/images/drawings/
    - assets/images/categories/abstract_and_surreal/
    - assets/images/categories/abstract_and_surreal/cubism/
    - assets/images/categories/abstract_and_surreal/dreamscapes/
    - assets/images/categories/abstract_and_surreal/fluid_art/
    - assets/images/categories/animals/
    - assets/images/categories/animals/birds/
    - assets/images/categories/animals/insects/
    - assets/images/categories/animals/marine_life/
    - assets/images/categories/animals/pets/
    - assets/images/categories/animals/wildlife/
    - assets/images/categories/careers_and_professions/
    - assets/images/categories/careers_and_professions/agriculture/
    - assets/images/categories/careers_and_professions/construction/
    - assets/images/categories/careers_and_professions/education/
    - assets/images/categories/careers_and_professions/healthcare/
    - assets/images/categories/careers_and_professions/public_safety/
    - assets/images/categories/characters/
    - assets/images/categories/characters/anime_manga/
    - assets/images/categories/characters/chibi/
    - assets/images/categories/characters/fashion/
    - assets/images/categories/characters/professions/
    - assets/images/categories/dark_and_gothic/
    - assets/images/categories/dark_and_gothic/dark_fantasy/
    - assets/images/categories/dark_and_gothic/monsters/
    - assets/images/categories/dark_and_gothic/skulls_and_bones/
    - assets/images/categories/events/
    - assets/images/categories/events/birthdays/
    - assets/images/categories/events/christmas/
    - assets/images/categories/events/halloween/
    - assets/images/categories/events/lunar_new_year/
    - assets/images/categories/fairytales_and_stories/
    - assets/images/categories/fairytales_and_stories/alice_in_wonderland/
    - assets/images/categories/fairytales_and_stories/book_illustrations/
    - assets/images/categories/fairytales_and_stories/classic_fables/
    - assets/images/categories/fantasy/
    - assets/images/categories/fantasy/magic_world/
    - assets/images/categories/fantasy/mythical_creatures/
    - assets/images/categories/fantasy/sci_fi/
    - assets/images/categories/fantasy/steampunk/
    - assets/images/categories/forbaby/
    - assets/images/categories/forbaby/animals/
    - assets/images/categories/forbaby/cartoons/
    - assets/images/categories/forbaby/families/
    - assets/images/categories/forbaby/fruits/
    - assets/images/categories/forbaby/numbers/
    - assets/images/categories/forbaby/trends/
    - assets/images/categories/forbaby/vegetations/
    - assets/images/categories/forme/
    - assets/images/categories/history_and_eras/
    - assets/images/categories/history_and_eras/ancient_world/
    - assets/images/categories/history_and_eras/medieval_times/
    - assets/images/categories/history_and_eras/wild_west/
    - assets/images/categories/kids_basics/
    - assets/images/categories/kids_basics/alphabets/
    - assets/images/categories/kids_basics/numbers/
    - assets/images/categories/kids_basics/simple_shapes/
    - assets/images/categories/lifestyle/
    - assets/images/categories/lifestyle/architecture/
    - assets/images/categories/lifestyle/food_and_drinks/
    - assets/images/categories/lifestyle/interiors/
    - assets/images/categories/lifestyle/vehicles/
    - assets/images/categories/lifestyle/vintage_retro/
    - assets/images/categories/military_and_forces/
    - assets/images/categories/military_and_forces/air_force/
    - assets/images/categories/military_and_forces/army/
    - assets/images/categories/military_and_forces/navy/
    - assets/images/categories/military_and_forces/special_forces/
    - assets/images/categories/music_and_arts/
    - assets/images/categories/music_and_arts/dance_styles/
    - assets/images/categories/music_and_arts/musical_instruments/
    - assets/images/categories/music_and_arts/theater_and_drama/
    - assets/images/categories/nature/
    - assets/images/categories/nature/botanical/
    - assets/images/categories/nature/flowers/
    - assets/images/categories/nature/landscapes/
    - assets/images/categories/nature/space_and_sky/
    - assets/images/categories/patterns/
    - assets/images/categories/patterns/geometric/
    - assets/images/categories/patterns/mandalas/
    - assets/images/categories/patterns/optical_illusions/
    - assets/images/categories/patterns/zentangles/
    - assets/images/categories/science_and_education/
    - assets/images/categories/science_and_education/anatomy/
    - assets/images/categories/science_and_education/machinery_parts/
    - assets/images/categories/science_and_education/micro_world/
    - assets/images/categories/spirituality/
    - assets/images/categories/spirituality/astrology_tarot/
    - assets/images/categories/spirituality/religions/
    - assets/images/categories/spirituality/zen_and_meditation/
    - assets/images/categories/sports_and_action/
    - assets/images/categories/sports_and_action/extreme_sports/
    - assets/images/categories/sports_and_action/martial_arts/
    - assets/images/categories/sports_and_action/team_sports/
    - assets/images/categories/tattoo_art/
    - assets/images/categories/tattoo_art/japanese_irezumi/
    - assets/images/categories/tattoo_art/traditional_tattoo/
    - assets/images/categories/tattoo_art/tribal_and_maori/
    - assets/images/categories/travel_and_places/
    - assets/images/categories/travel_and_places/cityscapes/
    - assets/images/categories/travel_and_places/cultural_outfits/
    - assets/images/categories/travel_and_places/world_landmarks/
    - assets/images/categories/typography/
    - assets/images/categories/typography/calligraphy/
    - assets/images/categories/typography/graffiti_art/
    - assets/images/categories/typography/inspirational_quotes/
    - assets/images/categories/vietnamese_heritage/
    - assets/images/categories/vietnamese_heritage/daily_life_past/
    - assets/images/categories/vietnamese_heritage/folklore_and_myths/
    - assets/images/categories/vietnamese_heritage/historical_figures/
    - assets/images/categories/vietnamese_heritage/patriotic_themes/
    - assets/images/categories/vietnamese_heritage/traditional_festivals/
    - assets/images/categories/world_and_nations/
    - assets/images/categories/world_and_nations/cultural_symbols/
    - assets/images/categories/world_and_nations/national_flags/
    - assets/images/categories/world_and_nations/traditional_costumes/
    - assets/images/categories/world_and_nations/world_maps/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
